import { NextResponse } from "next/server";
import { cookies } from "next/headers";

type WebsiteFile = {
  path: string;
  content: string;
};

function cleanText(value: unknown, fallback = "") {
  if (typeof value !== "string") return fallback;
  return value.trim();
}

function safeRepoName(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9-_]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);
}

function encodeBase64(content: string) {
  return Buffer.from(content, "utf8").toString("base64");
}

async function githubRequest(
  token: string,
  url: string,
  options: RequestInit = {}
) {
  const response = await fetch(url, {
    ...options,
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${token}`,
      "X-GitHub-Api-Version": "2022-11-28",
      "Content-Type": "application/json",
      ...(options.headers || {}),
    },
  });

  const data = await response.json().catch(() => null);

  if (!response.ok) {
    throw new Error(
      data?.message || `GitHub request failed with status ${response.status}`
    );
  }

  return data;
}

export async function POST(req: Request) {
  try {
    const cookieStore = await cookies();
    const githubToken = cookieStore.get("github_access_token")?.value;

    if (!githubToken) {
      return NextResponse.json(
        { error: "GitHub is not connected. Please connect GitHub first." },
        { status: 401 }
      );
    }

    const body = await req.json();

    const requestedRepoName = cleanText(body?.repoName);
    const description = cleanText(
      body?.description,
      "Generated by KORAX Website Builder AI"
    );
    const privateRepo = Boolean(body?.privateRepo);
    const files = body?.files as WebsiteFile[];

    if (!Array.isArray(files) || files.length === 0) {
      return NextResponse.json(
        { error: "Website files are required." },
        { status: 400 }
      );
    }

    const repoName = safeRepoName(requestedRepoName || "korax-generated-site");

    if (!repoName) {
      return NextResponse.json(
        { error: "Invalid repository name." },
        { status: 400 }
      );
    }

    const user = await githubRequest(
      githubToken,
      "https://api.github.com/user",
      { method: "GET" }
    );

    const owner = user.login;

    const repo = await githubRequest(
      githubToken,
      "https://api.github.com/user/repos",
      {
        method: "POST",
        body: JSON.stringify({
          name: repoName,
          description,
          private: privateRepo,
          auto_init: true,
        }),
      }
    );

    const uploaded: string[] = [];

    for (const file of files) {
      const cleanPath = cleanText(file.path).replace(/^\/+/, "");
      const content = typeof file.content === "string" ? file.content : "";

      if (!cleanPath || !content) continue;

      await githubRequest(
        githubToken,
        `https://api.github.com/repos/${owner}/${repoName}/contents/${encodeURIComponent(
          cleanPath
        ).replace(/%2F/g, "/")}`,
        {
          method: "PUT",
          body: JSON.stringify({
            message: `Add ${cleanPath}`,
            content: encodeBase64(content),
          }),
        }
      );

      uploaded.push(cleanPath);
    }

    return NextResponse.json({
      ok: true,
      owner,
      repoName,
      repoUrl: repo.html_url,
      uploaded,
      note: "Published through GitHub OAuth. Token is stored only in an httpOnly session cookie.",
    });
  } catch (error: any) {
    return NextResponse.json(
      {
        error: error?.message || "GitHub publish failed.",
      },
      { status: 500 }
    );
  }
}