import { NextRequest, NextResponse } from "next/server";

export const dynamic = "force-dynamic";
export const revalidate = 0;
export const runtime = "nodejs";

function cleanProjectName(value: string) {
  return (
    value
      ?.toLowerCase()
      .replace(/[^a-z0-9-]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 60) || "korax-generated-site"
  );
}

function getGithubRepoParts(repoUrl: string) {
  try {
    const url = new URL(repoUrl);

    if (!url.hostname.includes("github.com")) {
      throw new Error("Only GitHub repository URLs are supported.");
    }

    const parts = url.pathname
      .replace(/^\/+/, "")
      .replace(/\.git$/, "")
      .split("/")
      .filter(Boolean);

    if (parts.length < 2) {
      throw new Error("Invalid GitHub repository URL.");
    }

    return {
      owner: parts[0],
      repo: parts[1],
      fullName: `${parts[0]}/${parts[1]}`,
    };
  } catch {
    throw new Error("Invalid GitHub repository URL.");
  }
}

function defaultHtml(projectName: string) {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>${projectName}</title>
  <style>
    body {
      margin: 0;
      min-height: 100vh;
      display: grid;
      place-items: center;
      background: radial-gradient(circle at top, #12314f, #020617 55%, #000);
      color: white;
      font-family: Arial, sans-serif;
    }
    .card {
      width: min(920px, calc(100% - 32px));
      border: 1px solid rgba(255,255,255,.12);
      border-radius: 28px;
      padding: 42px;
      background: rgba(255,255,255,.06);
      box-shadow: 0 30px 100px rgba(0,0,0,.45);
      backdrop-filter: blur(18px);
    }
    .badge {
      display: inline-flex;
      border: 1px solid rgba(124,255,106,.35);
      color: #c4ffbc;
      border-radius: 999px;
      padding: 8px 14px;
      font-size: 13px;
      margin-bottom: 18px;
    }
    h1 {
      margin: 0;
      font-size: clamp(42px, 7vw, 82px);
      letter-spacing: -0.06em;
    }
    p {
      color: rgba(255,255,255,.7);
      font-size: 18px;
      line-height: 1.7;
      max-width: 700px;
    }
    button {
      margin-top: 18px;
      border: 0;
      border-radius: 999px;
      padding: 14px 22px;
      background: #7CFF6A;
      color: #031307;
      font-weight: 800;
      cursor: pointer;
    }
  </style>
</head>
<body>
  <main class="card">
    <div class="badge">Generated by KORAX Website Builder AI</div>
    <h1>${projectName}</h1>
    <p>
      This is a live deployment created through KORAX using the connected Vercel OAuth account.
      Next step: replace this test page with the full AI-generated Web3 website.
    </p>
    <button onclick="alert('Connect Wallet template will be added next.')">
      Connect Wallet
    </button>
  </main>
</body>
</html>`;
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.json().catch(() => ({}));

    const cookieToken = req.cookies.get("vercel_access_token")?.value || "";

    const bodyToken =
      typeof body?.vercelToken === "string" ? body.vercelToken.trim() : "";

    const vercelToken = cookieToken || bodyToken;

    const githubRepoUrl =
      typeof body?.githubRepoUrl === "string" ? body.githubRepoUrl.trim() : "";

    const rawProjectName =
      typeof body?.projectName === "string" ? body.projectName.trim() : "";

    const projectName = cleanProjectName(rawProjectName || "korax-generated-site");

    const branch =
      typeof body?.branch === "string" && body.branch.trim()
        ? body.branch.trim()
        : "main";

    const html =
      typeof body?.html === "string" && body.html.trim()
        ? body.html
        : "";

    if (!vercelToken) {
      return NextResponse.json(
        {
          ok: false,
          error:
            "Vercel is not connected. Please connect Vercel first or provide vercelToken.",
        },
        { status: 401 }
      );
    }

    /**
     * MODE 1:
     * Old GitHub deployment flow.
     * If githubRepoUrl exists, keep the old behavior.
     */
    if (githubRepoUrl) {
      const { owner, repo, fullName } = getGithubRepoParts(githubRepoUrl);
      const name = cleanProjectName(rawProjectName || repo);

      const createProjectResponse = await fetch(
        "https://api.vercel.com/v10/projects",
        {
          method: "POST",
          headers: {
            Authorization: `Bearer ${vercelToken}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            name,
            framework: "nextjs",
            gitRepository: {
              type: "github",
              repo: fullName,
            },
          }),
        }
      );

      const createProjectData = await createProjectResponse.json();

      if (!createProjectResponse.ok) {
        return NextResponse.json(
          {
            ok: false,
            mode: "github",
            error:
              createProjectData?.error?.message ||
              createProjectData?.message ||
              "Failed to create Vercel project.",
            details: createProjectData,
          },
          { status: createProjectResponse.status }
        );
      }

      const deploymentResponse = await fetch(
        "https://api.vercel.com/v13/deployments",
        {
          method: "POST",
          headers: {
            Authorization: `Bearer ${vercelToken}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            name,
            target: "production",
            project: createProjectData.id,
            gitSource: {
              type: "github",
              repo,
              org: owner,
              ref: branch,
            },
          }),
        }
      );

      const deploymentData = await deploymentResponse.json();

      if (!deploymentResponse.ok) {
        return NextResponse.json(
          {
            ok: false,
            mode: "github",
            error:
              deploymentData?.error?.message ||
              deploymentData?.message ||
              "Project created, but deployment failed.",
            project: createProjectData,
            details: deploymentData,
          },
          { status: deploymentResponse.status }
        );
      }

      const deploymentUrl = deploymentData?.url
        ? `https://${deploymentData.url}`
        : "";

      return NextResponse.json({
        ok: true,
        success: true,
        mode: "github",
        projectId: createProjectData.id,
        projectName: createProjectData.name || name,
        deploymentId: deploymentData.id,
        deploymentUrl,
        project: createProjectData,
        deployment: deploymentData,
      });
    }

    /**
     * MODE 2:
     * New Website Builder AI direct deployment flow.
     * No GitHub repo needed.
     */
    const finalHtml = html || defaultHtml(projectName);

    const deploymentPayload = {
      name: projectName,
      project: projectName,
      target: "production",
      files: [
        {
          file: "index.html",
          data: finalHtml,
        },
      ],
      projectSettings: {
        framework: null,
      },
    };

    const deploymentResponse = await fetch(
      "https://api.vercel.com/v13/deployments",
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${vercelToken}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify(deploymentPayload),
      }
    );

    const deploymentData = await deploymentResponse.json();

    if (!deploymentResponse.ok) {
      return NextResponse.json(
        {
          ok: false,
          mode: "direct",
          error:
            deploymentData?.error?.message ||
            deploymentData?.message ||
            "Failed to create direct Vercel deployment.",
          details: deploymentData,
        },
        { status: deploymentResponse.status }
      );
    }

    const deploymentUrl = deploymentData?.url
      ? `https://${deploymentData.url}`
      : "";

    return NextResponse.json({
      ok: true,
      success: true,
      mode: "direct",
      message: "Direct deployment created successfully.",
      projectName,
      deploymentId: deploymentData.id,
      deploymentUrl,
      deployment: deploymentData,
    });
  } catch (err: any) {
    return NextResponse.json(
      {
        ok: false,
        error: err?.message || "Unexpected Vercel deployment error.",
      },
      { status: 500 }
    );
  }
}